SHADOW_CASTING=true
SHADOW_QTY_SLIDER=1
SHADOW_DISTANCE_SLIDER=0
REFLECTION_SLIDER=2
DOF=false
DOF_STRENGTH=0.09
AO=1
AOSTEPS=5
AO_STRENGTH=0.70
AA_TYPE=2
MOTION_BLUR=false
REFRACTION=1
SUN_REFLECTION=1
WAVING=1
V_CLOUDS=1
CLOUD_STEPS_AVG=10
CLOUD_VOL_STYLE=0
BLOOM_SAMPLES=3.0
BLOOM=true
CHROMA_ABER=0
VOL_LIGHT=1
CLOUD_REFLECTION=true
WATER_ABSORPTION=0.10
COLOR_SCHEME=1
VANILLA_WATER=false
WATER_COLOR_SOURCE=0
COLORED_SHADOW=false
MOTION_BLUR_SAMPLES=4
MATERIAL_GLOSS=true
